version: "2"
services:

    frpstunnel:
        container_name: baibai-frpstunnel
        restart: always
        logging:
            driver: none
        image: registry.cn-hangzhou.aliyuncs.com/baibaicloud/baibai-frp:1.0.1
        network_mode: "host"
        volumes:
            - "/data/frpstunnel/logs:/logs"
            - "/data/frpstunnel/frps.ini:/frps.ini"
            
    frpscontrol:
        container_name: baibai-frpscontrol
        restart: always
        logging:
            driver: none
        image: registry.cn-hangzhou.aliyuncs.com/baibaicloud/baibai-frp:1.0.1
        network_mode: "host"
        volumes:
            - "/data/frpscontrol/logs:/logs"
            - "/data/frpscontrol/frps.ini:/frps.ini"

    mysql:
        container_name: baibai-mysql
        restart: always
        logging:
            driver: none
        image: registry.cn-hangzhou.aliyuncs.com/baibaicloud/mysql:5.7
        network_mode: "host"
        volumes:
            - "/data/mysql/initdb:/docker-entrypoint-initdb.d"
            - "/data/mysql/data:/var/lib/mysql"
        environment:
            # 环境变量 ieED!0dj5d5ie!kdkd
            - MYSQL_ROOT_PASSWORD=123456

    guacd:
        container_name: baibai-guacd
        restart: always
        logging:
            driver: none
        image: registry.cn-hangzhou.aliyuncs.com/baibaicloud/guacamole-guacd:1.2.0
        network_mode: "host"
        
    platform:
        container_name: baibai-platform
        restart: always
        logging:
            driver: none
        image: registry.cn-hangzhou.aliyuncs.com/baibaicloud/baibai-platform:1.0.0
        network_mode: "host"
        depends_on:
            - mysql
        volumes:
            - "/data/platform/logs:/logs"
        environment:
            # 环境变量
            - PARAMS=--server.port=8080 --frp.server.address=192.168.88.135 --frptunnel.server.address=192.168.88.135 --guac.guac.hostname=192.168.88.135